### ISSUE TITLE
Cloud foundry sample is giving wrong containerisation options

### ISSUE THREAD

**Issue by ashokponkumar** [konveyor/move2kube-demos#19]

**Comment by ashokponkumar** [comment]
Duplicate of https://github.com/konveyor/move2kube/issues/140

**Comment by ashokponkumar** [comment]
This might have been fixed in the latest release. Lets ensure we are getting the right plan file for our cloud foundry sample.

**Comment by Akash-Nayak** [comment]
This is the new plan file for our cloud foundry sample.

```
apiVersion: move2kube.konveyor.io/v1alpha1
 kind: Plan
 metadata:
   name: myproject
 spec:
   inputs:
     rootDir: cloud-foundry
     services:
       move2kube-demo-cf:
         - serviceName: move2kube-demo-cf
           serviceRelPath: /move2kube-demo-cf
           image: move2kube-demo-cf:latest
           translationType: Cfmanifest2Kube
           containerBuildType: NewDockerfile
           sourceType:
             - Directory
             - CfManifest
           targetOptions:
             - m2kassets/dockerfiles/nodejs
           sourceArtifacts:
             CfManifest:
               - manifest.yml
             CfRunningManifest:
               - cfapps.yaml
             SourceCode:
               - .
           buildArtifacts:
             SourceCode:
               - .
           updateContainerBuildPipeline: true
           updateDeployPipeline: true
         - serviceName: move2kube-demo-cf
           serviceRelPath: /move2kube-demo-cf
           image: move2kube-demo-cf:latest
           translationType: Cfmanifest2Kube
           containerBuildType: S2I
           sourceType:
             - Directory
             - CfManifest
           targetOptions:
             - m2kassets/s2i/nodejs
           sourceArtifacts:
             CfManifest:
               - manifest.yml
             CfRunningManifest:
               - cfapps.yaml
             SourceCode:
               - .
           buildArtifacts:
             SourceCode:
               - .
           updateContainerBuildPipeline: true
           updateDeployPipeline: true
         - serviceName: move2kube-demo-cf
           serviceRelPath: /move2kube-demo-cf
           image: move2kube-demo-cf:latest
           translationType: Cfmanifest2Kube
           containerBuildType: CNB
           sourceType:
             - Directory
             - CfManifest
           targetOptions:
             - cloudfoundry/cnb:cflinuxfs3
             - gcr.io/buildpacks/builder
           sourceArtifacts:
             CfManifest:
               - manifest.yml
             CfRunningManifest:
               - cfapps.yaml
             SourceCode:
               - .
           buildArtifacts:
             SourceCode:
               - .
           updateContainerBuildPipeline: true
           updateDeployPipeline: true
     targetInfoArtifacts:
       KubernetesCluster:
         - cluster.yaml
   outputs:
     kubernetes:
       artifactType: Yamls
       targetCluster:
         type: |
           default/c114-e-us-south-containers-cloud-ibm-com:32230/
       ignoreUnsupportedKinds: true
```
